/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mibprojekt;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @author Felix
 */
public class Andra_Kontorschef extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form Andra_Kontorschef
     */
    public Andra_Kontorschef(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllcbAgentID();
        fyllcbKontor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbAgentID = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbKontor = new javax.swing.JComboBox<>();
        labelAgentID = new javax.swing.JLabel();
        btnKontorschef = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(cbAgentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 130, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Update Office Manager");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        getContentPane().add(cbKontor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 130, -1));

        labelAgentID.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        labelAgentID.setForeground(new java.awt.Color(255, 255, 255));
        labelAgentID.setText("Agent ID:");
        getContentPane().add(labelAgentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        btnKontorschef.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnKontorschef.setText("Update Office Manager");
        btnKontorschef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKontorschefActionPerformed(evt);
            }
        });
        getContentPane().add(btnKontorschef, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Office:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mibprojekt/pictures/Bild_Blank.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKontorschefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKontorschefActionPerformed
        String agentID = cbAgentID.getSelectedItem().toString();
        String kontor = cbKontor.getSelectedItem().toString();
        try {
            idb.update("UPDATE kontorschef SET agent_id = '" + agentID + "' WHERE kontorsbeteckning = '" + kontor + "'");
        } 
        catch (Exception annatUndantag) {
            JOptionPane.showMessageDialog(null, "Something went wrong. Please contact your IT-Administrator.");
            System.out.println("InternFelmeddelande:" + annatUndantag.getMessage());
        }
    }//GEN-LAST:event_btnKontorschefActionPerformed

    
        public void fyllcbAgentID() {
        String fraga = "SELECT agent_id FROM agent";

        ArrayList<String> allaAgentID;

        try {
            allaAgentID = idb.fetchColumn(fraga);
            for (String ID : allaAgentID) {
                cbAgentID.addItem(ID);
            }
        } catch (Exception annatUndantag) {
            JOptionPane.showMessageDialog(null, "Something went wrong. Please contact your IT-Administrator.");
            System.out.println("InternFelmeddelande:" + annatUndantag.getMessage());
        }
    }    
    
        public void fyllcbKontor() {
        String fraga = "SELECT kontorsbeteckning FROM kontorschef";

        ArrayList<String> allaKontor;

        try {
            allaKontor = idb.fetchColumn(fraga);
            for (String benamning : allaKontor) {
                cbKontor.addItem(benamning);
            }
        } catch (Exception annatUndantag) {
            JOptionPane.showMessageDialog(null, "Something went wrong. Please contact your IT-Administrator.");
            System.out.println("InternFelmeddelande:" + annatUndantag.getMessage());
        }
    }
           
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Andra_Kontorschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Andra_Kontorschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Andra_Kontorschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Andra_Kontorschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Andra_Kontorschef().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKontorschef;
    private javax.swing.JComboBox<String> cbAgentID;
    private javax.swing.JComboBox<String> cbKontor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelAgentID;
    // End of variables declaration//GEN-END:variables
}
