/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mibprojekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @author trnfa
 */
public class EditAgent extends javax.swing.JFrame {

    /**
     * Creates new form EditAgent
     */
    private static InfDB idb;
    private String namn;
    private static String id;
    private String datum;
    private String telefon;
    private String omrade;
    private String isAdmin;  
    
    public EditAgent(InfDB idb, String namn, String id, String datum, String telefon, String omrade, String isAdmin) {
        initComponents();
        this.idb= idb;
        this.namn = namn; 
        this.id = id;
        this.datum = datum;
        this.telefon = telefon;
        this.isAdmin = isAdmin;
        this.omrade = omrade;
        setStartText();
       // this.isAdmin = isAdmin;
    }
    public EditAgent(){
        initComponents();
    }
    
    private void setAdminStart(String isAdmin){
        switch(isAdmin){
            case"J":
                cbIsAdmin.setSelectedItem("Ja");
                break;
            case"N":
                cbIsAdmin.setSelectedItem("Nej");
                break;
        }
    }
    private String getAdmin(){
        String nyIsAdmin = null;
        if(cbIsAdmin.getSelectedItem() == "Ja"){
            nyIsAdmin =  "J";
        }
        else if (cbIsAdmin.getSelectedItem() == "Nej"){
            nyIsAdmin =  "N";
        }        
        else
               System.out.println("error");
        return nyIsAdmin;
    }
    private String setOmradeStart(String omrade){
        switch(omrade){
            case"1":
                cbOmrade.setSelectedItem("Svealand");
                break;
            case"2":
                cbOmrade.setSelectedItem("Götaland");
                break;
            case"4":
                cbOmrade.setSelectedItem("Norrland");
                break;
        }
        return omrade;
    }
    
    private String getOmrade(){
        String nyOmrade = null;
        if(cbOmrade.getSelectedItem() == "Svealand"){
            nyOmrade = "1";
        }
        else if (cbOmrade.getSelectedItem() == "Götaland"){
            nyOmrade = "2";
        }
        else if(cbOmrade.getSelectedItem() == "Norrland"){
            nyOmrade ="4";
        }
        else
            System.out.println("rror");
        return nyOmrade;
    }
    
    private void setStartText(){
        setOmradeStart(omrade);
        setAdminStart(isAdmin);
        lblID.setText(id);
        txtNamn.setText(namn);
        txtDatum.setText(datum);
        txtTelefon.setText(telefon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbIsAdmin = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txtDatum = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtNamn = new javax.swing.JTextField();
        cbOmrade = new javax.swing.JComboBox<>();
        lblID = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agent ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 40, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone Number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date of Employment:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Region:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Is Admin:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        cbIsAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nej", "Ja" }));
        getContentPane().add(cbIsAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 57, -1));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 73, -1));

        txtDatum.setText("jTextField3");
        getContentPane().add(txtDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 120, -1));

        txtTelefon.setText("jTextField4");
        getContentPane().add(txtTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 120, -1));

        txtNamn.setText("jTextField5");
        getContentPane().add(txtNamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 120, -1));

        cbOmrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Svealand", "Götaland", "Norrland" }));
        getContentPane().add(cbOmrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 88, -1));

        lblID.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("jLabel7");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        btnCancel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(873, 20, 110, -1));

        btnDelete.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 83, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Edit Agent Information");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mibprojekt/pictures/Bild_Blank.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(setNamn() && Validering.okPhoneNumber(txtTelefon) && Validering.isDate(txtDatum)){
            try{
                idb.fetchSingle("UPDATE agent SET namn = '"+ txtNamn.getText() + "' , telefon = '" + txtTelefon.getText() + "' , anstallningsdatum = '" + 
                    txtDatum.getText() + "' , omrade = " + getOmrade() + ", administrator = '" + getAdmin() + "' WHERE agent_id = " + id + ";");
            System.out.println("update OK");       
            dispose();
            }
            catch (Exception e){
                System.out.println("InternFelmeddelande:" + e.getMessage());  
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String input = "You are about to delete an Agent";
        new ControlWindow(input, "agent").setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDeleteActionPerformed
    
    public static boolean deleteAgent(){
        boolean raderad = false;
        try{
            idb.fetchSingle("DELETE FROM agent WHERE agent_id = " + id);
            raderad = true;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong.");
        }
        return raderad;
    }
    
    private boolean setNamn(){
        String forslagNamn = txtNamn.getText();
        boolean ok = false;
        if (Validering.textFaltHarVarde(txtNamn) && Validering.txtHarInteBaraSpace(txtNamn)){
            try {
                String nr = idb.fetchSingle("SELECT count(*) from agent where namn = '"+ forslagNamn + "'");
                int antal = Integer.valueOf(nr);
                if (antal == 0 || namn.equals(forslagNamn)){
                    namn = forslagNamn;
                    ok = true;
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please chose an unique name for the Agent.");
                }     
            }
            catch(Exception ettUndantag){
            JOptionPane.showMessageDialog(null, "Something went wrong");         
            }
        }
        return ok;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EditAgent(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cbIsAdmin;
    private javax.swing.JComboBox<String> cbOmrade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
