/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mibprojekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author trnfa
 */
public class RegAlien extends javax.swing.JFrame {

    /**
     * Creates new form RegAlien
     */
    private static InfDB idb;
    
    private static int alienID;
    private static String regDate;
    private static String losen;
    private static String namn;
    private static String telefon;
    private static int omrade;
    private static String ras;
    private static int rasBenamning;
    private static String ansvarigAgent;
    
    public RegAlien(InfDB idb) {
        initComponents();
        txtRasBenamning.setVisible(false);
        this.idb = idb;
        setAlienID();
        setAnsvarigAgent();
        setDate();
    }
    //konstruktor för att ändra alien info
    public RegAlien(InfDB idb, int alienID){
        initComponents();
        this.idb = idb;
        this.alienID = alienID;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAlienNamn = new javax.swing.JLabel();
        comboOmrade = new javax.swing.JComboBox<>();
        lblAlienID = new javax.swing.JLabel();
        lblTelnummer = new javax.swing.JLabel();
        lbllRegDatum = new javax.swing.JLabel();
        lblPlaceras = new javax.swing.JLabel();
        lblLosen = new javax.swing.JLabel();
        lblAnsvarigAgent = new javax.swing.JLabel();
        btnReg = new javax.swing.JButton();
        txtTelefon = new javax.swing.JTextField();
        txtNamn = new javax.swing.JTextField();
        txtLosen = new javax.swing.JPasswordField();
        txtLosenUpp = new javax.swing.JPasswordField();
        lblLosenUpp = new javax.swing.JLabel();
        lblVisaAnsvarigAgent = new javax.swing.JLabel();
        lblVisaDatum = new javax.swing.JLabel();
        lblVisaID = new javax.swing.JLabel();
        lblRas = new javax.swing.JLabel();
        comboRas = new javax.swing.JComboBox<>();
        lblRasBenamning = new javax.swing.JLabel();
        txtRasBenamning = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        lblRegisterNewAlien = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAlienNamn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblAlienNamn.setForeground(new java.awt.Color(255, 255, 255));
        lblAlienNamn.setText("Alien Name: *");
        getContentPane().add(lblAlienNamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        comboOmrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Örebro", "Västerås", "Vilhelmina", "Borås" }));
        comboOmrade.setDoubleBuffered(true);
        getContentPane().add(comboOmrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 140, -1));

        lblAlienID.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblAlienID.setForeground(new java.awt.Color(255, 255, 255));
        lblAlienID.setText("Alien ID:");
        getContentPane().add(lblAlienID, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        lblTelnummer.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblTelnummer.setForeground(new java.awt.Color(255, 255, 255));
        lblTelnummer.setText("Phone number:");
        getContentPane().add(lblTelnummer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        lbllRegDatum.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lbllRegDatum.setForeground(new java.awt.Color(255, 255, 255));
        lbllRegDatum.setText("Registration Date:");
        getContentPane().add(lbllRegDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 120, -1));

        lblPlaceras.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblPlaceras.setForeground(new java.awt.Color(255, 255, 255));
        lblPlaceras.setText("Placed in:");
        getContentPane().add(lblPlaceras, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        lblLosen.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblLosen.setForeground(new java.awt.Color(255, 255, 255));
        lblLosen.setText("Password:*");
        getContentPane().add(lblLosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        lblAnsvarigAgent.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblAnsvarigAgent.setForeground(new java.awt.Color(255, 255, 255));
        lblAnsvarigAgent.setText("Responsible Agent:");
        getContentPane().add(lblAnsvarigAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        btnReg.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnReg.setText("OK");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        getContentPane().add(btnReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 100, -1));
        getContentPane().add(txtTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 140, -1));
        getContentPane().add(txtNamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 140, -1));
        getContentPane().add(txtLosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 140, -1));
        getContentPane().add(txtLosenUpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 140, -1));

        lblLosenUpp.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblLosenUpp.setForeground(new java.awt.Color(255, 255, 255));
        lblLosenUpp.setText("Repeat Password:*");
        getContentPane().add(lblLosenUpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        lblVisaAnsvarigAgent.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblVisaAnsvarigAgent.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblVisaAnsvarigAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 130, 20));

        lblVisaDatum.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblVisaDatum.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblVisaDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 160, 20));

        lblVisaID.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblVisaID.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblVisaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 60, 20));

        lblRas.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblRas.setForeground(new java.awt.Color(255, 255, 255));
        lblRas.setText("Race:");
        getContentPane().add(lblRas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        comboRas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Worm", "Squid", "Boglodite" }));
        comboRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRasActionPerformed(evt);
            }
        });
        getContentPane().add(comboRas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 140, -1));

        lblRasBenamning.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblRasBenamning.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblRasBenamning, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 130, 20));
        getContentPane().add(txtRasBenamning, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 140, -1));

        btnCancel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 100, -1));

        lblRegisterNewAlien.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        lblRegisterNewAlien.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterNewAlien.setText("Register New Alien");
        getContentPane().add(lblRegisterNewAlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mibprojekt/pictures/Bild_Blank.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        setRas();
        setOmrade();
        if (setPW() && setNamn() && setTelefon() && setRasBenamning()){
                try{
                idb.fetchSingle("INSERT INTO alien (Alien_ID, Registreringsdatum, Losenord, Namn, Telefon, Plats, Ansvarig_agent)"
                    + "Values (" + alienID + ", ' " + regDate + "' , '" + losen + "' , '" + namn + "' , " + telefon + ", " + omrade + ", " + ansvarigAgent + ")");              
                switch(ras){
                    case "Worm":
                        idb.fetchSingle("INSERT INTO Worm (Alien_ID) VALUES (" + alienID + ")");
                        break;
                    case"Squid":
                        idb.fetchSingle("INSERT INTO Squid (Alien_ID, antal_Armar) VALUES (" + alienID + ", " + rasBenamning + ")");
                        break;
                    case "Boglodite":
                        idb.fetchSingle("INSERT INTO boglodite (Alien_ID, Antal_Boogies)VALUES (" + alienID + ", " + rasBenamning + ")");
                }
                
                    System.out.println("OK");
                    dispose();
                }
                
                catch (Exception ettUndantag){
                    System.out.println("InternFelmeddelande:" + ettUndantag.getMessage());  
                }
            }
    }//GEN-LAST:event_btnRegActionPerformed

    private void comboRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRasActionPerformed
       ras = comboRas.getSelectedItem().toString(); 
       switch(ras){
           case "Squid":
               lblRasBenamning.setText("Amount of Arms: ");
               txtRasBenamning.setVisible(true);
               break;
           case "Boglodite":
               lblRasBenamning.setText("Amount of Boogies: ");
               txtRasBenamning.setVisible(true);
               break;
           case "Worm":
               lblRasBenamning.setText(" ");
               txtRasBenamning.setVisible(false);
               break;
       }
    }//GEN-LAST:event_comboRasActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegAlien(idb).setVisible(true);
            }
        });
    }
    public void setDate(){
        regDate = "2022-05-19";
        lblVisaDatum.setText(regDate);
    }
    
    public boolean setAlienID(){
        boolean ok = true;
        try{
            int nyttID = Integer.parseInt(idb.fetchSingle("Select MAX(Alien_ID) from Alien"));
            nyttID++;
            alienID = nyttID;
            lblVisaID.setText(String.valueOf(alienID));
        }
        catch(Exception ettUndantag){
            JOptionPane.showMessageDialog(null, "Something went wrong. Please contact your IT-Administrator. is not Alien");
            System.out.println("InternFelmeddelande:" + ettUndantag.getMessage());         
            ok = false;
        }
        return ok;
    }
    
    public boolean setAnsvarigAgent(){
        boolean ok = true;
        try{
           lblVisaAnsvarigAgent.setText(idb.fetchSingle("SELECT Namn FROM Agent WHERE Agent_ID = '" + LoggedUser.getUserID() + "'"));
           ansvarigAgent = LoggedUser.getUserID();
        }
        catch(Exception ettUndantag){
            JOptionPane.showMessageDialog(null, "Something went wrong. Please contact your IT-Administrator. is not Alien");
            System.out.println("InternFelmeddelande:" + ettUndantag.getMessage());       
            ok = false;
        }
        return ok;
    }
    
    public boolean setPW(){
        boolean ok = true;
        String newPW = txtLosen.getText();
        String newPWUpp = txtLosenUpp.getText();
        
        if(Validering.losenOK(txtLosen)){
            if(newPW.equals(newPWUpp)){
                losen = newPW;
            }
            else{
                JOptionPane.showMessageDialog(null, "The two passwords does not match");
                ok = false;
            }
        } 
        else{
            ok = false;
        }
        return ok;
    }
    
    public boolean setNamn(){
        boolean ok = false;
        String forslagNamn = txtNamn.getText();
        if (Validering.textFaltHarVarde(txtNamn) && Validering.txtHarInteBaraSpace(txtNamn)){
           try {
                String nr = idb.fetchSingle("SELECT count(*) from alien where namn = '"+ forslagNamn + "'");
                int antal = Integer.valueOf(nr);
                if (antal == 0){
                    namn = forslagNamn;
                    ok = true;
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please chose an unique name for the Alien.");
                }     
            }
            catch(Exception ettUndantag){
            JOptionPane.showMessageDialog(null, "Something went wrong");         
            }
        }
        return ok;
    }  
    public void setOmrade(){
        String plats = comboOmrade.getSelectedItem().toString();
        switch(plats){
            case "Örebro":
                omrade = 1;
                break;
            case "Västerås":
                omrade = 2;
                break;
            case "Vilhelmina":
                omrade = 3;
                break;
            case "Borås":
                omrade = 4;
                break;
        }              
    }
    public boolean setRasBenamning(){
        boolean ok = false;
        if(ras.equals("Boglodite") || ras.equals("Squid")){ 
            if (Validering.textFaltHarVarde(txtRasBenamning) && Validering.isHeltal(txtRasBenamning)){
                rasBenamning = Integer.parseInt(txtRasBenamning.getText());
                ok = true;
            }
        }
        else if (ras.equals("Worm"))
            ok = true;
        
        return ok;
    }
    
    public void setRas(){
        ras = comboRas.getSelectedItem().toString();      
    }
    public boolean setTelefon(){    
        boolean resultat = false;
        if (txtTelefon.getText().equals("")){
            telefon = null;
            resultat = true;
        }
        else if(Validering.okPhoneNumber(txtTelefon)){
            telefon = txtTelefon.getText();
            resultat = true;
        }
        return resultat;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReg;
    private javax.swing.JComboBox<String> comboOmrade;
    private javax.swing.JComboBox<String> comboRas;
    private javax.swing.JLabel lblAlienID;
    private javax.swing.JLabel lblAlienNamn;
    private javax.swing.JLabel lblAnsvarigAgent;
    private javax.swing.JLabel lblLosen;
    private javax.swing.JLabel lblLosenUpp;
    private javax.swing.JLabel lblPlaceras;
    private javax.swing.JLabel lblRas;
    private javax.swing.JLabel lblRasBenamning;
    private javax.swing.JLabel lblRegisterNewAlien;
    private javax.swing.JLabel lblTelnummer;
    private javax.swing.JLabel lblVisaAnsvarigAgent;
    private javax.swing.JLabel lblVisaDatum;
    private javax.swing.JLabel lblVisaID;
    private javax.swing.JLabel lbllRegDatum;
    private javax.swing.JPasswordField txtLosen;
    private javax.swing.JPasswordField txtLosenUpp;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtRasBenamning;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
