package mibprojekt;

import oru.inf.InfDB;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author trnfa
 */
public class Startsida_Alien extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form Startsida
     */
    public Startsida_Alien(InfDB idb) {
        initComponents();
        this.idb = idb;
        ansvarigAgent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lableAnsvarigAgent = new javax.swing.JLabel();
        cbLoggaUt = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 563));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lableAnsvarigAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 220, 190));

        cbLoggaUt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Logga ut", "Ändra Lösenord" }));
        cbLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoggaUtActionPerformed(evt);
            }
        });
        getContentPane().add(cbLoggaUt, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 30, 90, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mibprojekt/pictures/Bild_Startsida_Alien.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoggaUtActionPerformed
        String action = cbLoggaUt.getSelectedItem().toString();
        switch(action){
            case "Logga ut":
                System.exit(0);
                break;
            case "Ändra Lösenord":
                new BytLosen(idb).setVisible(true);
                dispose();
                break;
        }  
    }//GEN-LAST:event_cbLoggaUtActionPerformed


    public void ansvarigAgent(){
        //     jTextField1.setText(onlyDate.format(date));
    //jLabel1.setText(jTextField1.getText());
    try{
        String aAID = idb.fetchSingle("SELECT Ansvarig_Agent FROM alien WHERE Alien_ID = '" + LoggedUser.getUserID() + "'");
        String aA = idb.fetchSingle("SELECT Namn FROM agent WHERE Agent_ID = '" + aAID + "'");
        //lableAnsvarigAgent.setText(aA);
        lableAnsvarigAgent.setText(aA);
        }
        catch (Exception ettUndantag){
            //     JOptionPane.showMessageDialog(null, "Something went wrong. Please contact your IT-Administrator.");
            System.out.println("InternFelmeddelande:" + ettUndantag.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> cbLoggaUt;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lableAnsvarigAgent;
    // End of variables declaration//GEN-END:variables
}
